# numpy

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
matrix=np.array([[1,2,3],[4,5,6,7]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [6]:
matrix=np.array([[1,2,3,4],[4,5,6,7]])

In [8]:
print(matrix)

[[1 2 3 4]
 [4 5 6 7]]


In [9]:
arr.shape

(5,)

In [10]:
matrix.shape

(2, 4)

In [11]:
matrix.dtype

dtype('int32')

In [12]:
matrix[0,0]=5

In [14]:
matrix

array([[5, 2, 3, 4],
       [4, 5, 6, 7]])

In [15]:
matrix[0,0]='omkar'

ValueError: invalid literal for int() with base 10: 'omkar'

In [17]:
matrix[0][0]

5

In [18]:
matrix[0,0]

5

In [19]:
mat2= np.arange(0,20,3)

In [20]:
mat2

array([ 0,  3,  6,  9, 12, 15, 18])

In [21]:
mat3= np.linspace(0,10,20)

In [22]:
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [23]:
mat4= np.random.rand(5,5)
mat4

array([[0.37306459, 0.52219643, 0.38066122, 0.46863924, 0.45223796],
       [0.46554861, 0.48137786, 0.24559465, 0.67248227, 0.10246382],
       [0.11101317, 0.33688834, 0.37799948, 0.04832255, 0.79830462],
       [0.23305555, 0.76596968, 0.78063091, 0.52203159, 0.74010664],
       [0.76512205, 0.42811245, 0.46446513, 0.69095963, 0.84677347]])

In [26]:
mat5= np.random.randn(5,4) #normally distributed random numbers

In [27]:
mat5

array([[-0.00546909, -1.90066008,  1.06340163,  0.28377337],
       [ 0.50741846, -0.65922443, -0.43341417, -0.28779129],
       [-0.37619537, -1.065879  , -0.37236786, -0.01586184],
       [ 1.09795553,  0.24892537, -0.19060065,  0.57834533],
       [ 1.11742038, -0.18062418, -0.70448166,  0.07242608]])

In [31]:
#diagonal matrix
mat6=np.diag([1,2,3,4,5])
mat6

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [39]:
mat7=np.zeros(10)
mat7

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
mat8=np.ones(10)
mat8

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])