# numpy

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
matrix=np.array([[1,2,3],[4,5,6]])

In [6]:
matrix=np.array([[1,2,3,4],[4,5,6,7]])

In [7]:
print(matrix)

[[1 2 3 4]
 [4 5 6 7]]


In [8]:
arr.shape

(5,)

In [9]:
matrix.shape

(2, 4)

In [10]:
matrix.dtype

dtype('int32')

In [11]:
matrix[0,0]=5

In [12]:
matrix

array([[5, 2, 3, 4],
       [4, 5, 6, 7]])

In [13]:
matrix[0,0]='omkar'

ValueError: invalid literal for int() with base 10: 'omkar'

In [ ]:
matrix[0][0]

In [ ]:
matrix[0,0]

In [ ]:
mat2= np.arange(0,20,3)

In [ ]:
mat2

In [ ]:
mat3= np.linspace(0,10,20)

In [ ]:
mat3

In [ ]:
mat4= np.random.rand(5,5)
mat4

In [ ]:
mat5= np.random.randn(5,4) #normally distributed random numbers

In [ ]:
mat5

In [ ]:
#diagonal matrix
mat6=np.diag([1,2,3,4,5])
mat6

In [ ]:
mat7=np.zeros(10)
mat7

In [ ]:
mat8=np.ones(10)
mat8